default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5434
  username: rails
  password: rails
  host: localhost

development:
  <<: *default
  database: penopen_api_development2

test:
  <<: *default
  database: penopen_api_test2

production:
  <<: *default
